name: Create Blank Wiki Page

on:
  workflow_dispatch:
    inputs:
      page_name:
        description: 'Name of the new wiki page (without .md)'
        required: true

jobs:
  create-wiki-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wiki repo
        run: |
          git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git" wiki
      - name: Create blank page
        run: |
          cd wiki
          touch "${{ github.event.inputs.page_name }}.md"
      - name: Commit and push
        run: |
          cd wiki
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add "${{ github.event.inputs.page_name }}.md"
          git commit -m "Add blank wiki page: ${{ github.event.inputs.page_name }}"
          git push
